### Listar produtos
GET http://localhost:3333/produtos

###

### Criar produto
POST http://localhost:3333/produtos
Content-Type: application/json

{
    "name": "The Handy",
    "descricao": "Ótima para se divertir"
}

###

### Atualizar produto
PUT http://localhost:3333/produtos/4151cdae-838d-4f11-b9a2-3d447e4310d4
Content-Type: application/json

{
    "name": "O Mãozinha",
    "descricao": "Produto de alta qualidade"
}

###

### Deletar produto
DELETE http://localhost:3333/produtos/4151cdae-838d-4f11-b9a2-3d447e4310d4
