### Listar produtos
GET http://localhost:3333/produtos

###

### Criar produto
POST http://localhost:3333/produtos
Content-Type: application/json

{
    "name": "Insane Clown",
    "descricao": "Pra treinar potente!"
}

###

### Atualizar produto
PUT http://localhost:3333/produtos/id
Content-Type: application/json

{
    "name": "Palhaço Insano",
    "descricao": "Pré treino mais forte do mercado."
}

###

### Deletar produto
DELETE http://localhost:3333/produtos/id
